import React from 'react';
import Head from 'next/head';
import Layout from '@/components/layout/Layout';
import AccountSection from '@/components/AccountSection';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function Home() {
    const { data: session, status } = useSession();
    const router = useRouter();

    useEffect(() => {
        if (status === 'unauthenticated') {
            router.push('/signin');
        }
    }, [status, router]);

    if (status === 'loading' || status === 'unauthenticated') {
        return null;
    }

    return (
        <>
            <Head>
                <title>Salesforce NextAuth Demo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <AccountSection />
            </Layout>
        </>
    );
}
